-- USER
CREATE TABLE USER (
    ID VARCHAR2,
    PWD VARCHAR2,
    NAME VARCHAR2,
    EMAIL VARCHAR2,
    NICNAME VARCHAR2,
    PRIMARY KEY(ID)
);

-- BOARD
CREATE TABLE BOARD (
    BOARDNO NUMBER,
    BOARDNAME VARCHAR2,
    BOARDLOCATION VARCHAR2,
    BOARDHOURS DATE,
    BOARDINFO VARCHAR,
    STARS NUMBER,
    PRIMARY KEY(BOARDNO)
);

-- REVIEW
CREATE TABLE REVIEW (
    REVIEWNO NUMBER,
    COMMENT VARCHAR,
    REVIEWTIME DATE,
    FOREIGN KEY(LOCALNO) REFERENCES BOARD(BOARDNO),
    FOREIGN KEY(USERID) REFERENCES USER(ID),
    PRIMARY KEY(REVIEWNO),
    PRIMARY KEY(BOARDNO)
);

-- QUIZ
CREATE TABLE QUIZ (
    QUIZNO NUMBER,
    QUESTTION VARCHAR2,
    RESULT VARCHAR2,
    PRIMARY KEY(QUIZNO)
);